version: "3.8"

services:

  frontend:
    build: ../frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    env_file:
      - ../frontend/.env
    develop:
      watch:
        - action: rebuild
          path: ../frontend/package.json
        - action: rebuild
          path: ../frontend/pnpm-lock.yaml

  backend:
    build: .
    ports:
      - "5278:5278"
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5278
      - ASPNETCORE_ENVIRONMENT=Development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - bin/
            - obj/
            - .git/
            - docker-compose.yml
